spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    url: jdbc:mysql://127.0.0.1:3306/db_kms_zipkin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456