spring:
  application:
    name: kentra-cms-auth #系统基础服务api项目名称
#  security:
#    user:
#      name: "admin"
#      password: "123456"

#  sleuth:
#    web:
#      client:
#        enabled: true
#    sampler:
#      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#  zipkin:
#    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
server:
  port: 8766 #系统基础服务api项目端口号